// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"TerraxLighting","status":false,"description":"v1.4.6 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"300","Add to options":"No","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"866","Screensize Y":"630","Kill Switch":"No"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}},
{"name":"OrangeLighting","status":false,"description":"Lighting system <OrangeLighting>","parameters":{"lightMaskSwitch":"0","opacityVariable":"0","tintSpeed":"0.3","defaultMaskColor":"black"}},
{"name":"OrangeLightingPlayerLight","status":false,"description":"Player Lights <OrangeLightingPlayerLight>","parameters":{"playerRadius":"300","playerColor":"#FFFFFF","playerFlicker":"true","flashlightSwitch":"0"}},
{"name":"OrangeLightingEventLight","status":false,"description":"Event Lights <OrangeLightingEventLight>","parameters":{"eventRadius":"300","eventColor":"#FFFFFF","eventFlicker":"true"}}
];
